# Generated by Django 3.0.5 on 2020-10-01 11:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_created', models.DateTimeField(default=datetime.datetime(2020, 10, 1, 11, 34, 11, 684764), verbose_name='Время создания')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('PLANNED', 'Запланированная'), ('ON-THE-JOB', 'В работе'), ('FINISHED', 'Завершенная')], default='NEW', max_length=10, verbose_name='Статус')),
                ('planned_finish_time', models.DateTimeField(blank=True, verbose_name='Планируемое время завершения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
