# Generated by Django 3.0.5 on 2020-10-07 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201007_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 8, 2, 56, 174019), verbose_name='Время создания'),
        ),
    ]
